version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot:latest
    stop_grace_period: 0s
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - "./:/app"
    command: python3 app.py
    # command: sleep infinity
    tty: true
